### ISSUE TITLE
Slimefun (add-on) ExtraHeads: does not load the texture of some heads!

### ISSUE THREAD

**Issue by ThatsCube** [TheBusyBiscuit/ExtraHeads#1]
I just installed this add-on and as the title suggests, I encountered a problem.
Most of the heads are not loaded. I tried to update everything but nothing.

_I think it's a problem with this add-on, since the rest of the heads like food and pets are working properly._

**Screenshot**:
https://imgur.com/a/jcq8srU

**Plugins (36)**: EZColors, dynmap, LuckPerms, WorldEdit, LoginSecurity, PlaceholderAPI, MySkin, WorldGuard, WolfyUtilities, KixsChatAnnouncer, SurvivalPlus, RandomTeleport, EasyWhitelist, MOTD, CS-CoreLib, Vault, Statz, SimpleScore, Essentials, CustomCrafting, KillerMoney, ActionHealth, Shopkeepers, Slimefun, BetterSleeping, EmeraldEnchants, HotbarPets, SlimefunLuckyBlocks, EssentialsChat, ExoticGarden, Barrels, SoulJars, EssentialsSpawn, ExtraGear, ExtraHeads, PrivateStorage

**-**     Minecraft Version: **1.14.4**
**-**     Server: **Spigot**
**-**     Slimefun Version: **DEV 259**
**-**     CS-CoreLib Version: **DEV 76**

**Comment by TheBusyBiscuit** [comment]
The heads are rendered client-side, so it is definitely not a problem with this plugin, it uses the same mechanic as all the other Addons.

The only way something like that could happen is if Mojangs Servers are having problems, your server runs in offline mode or it could be a caching problem.
But definitely not caused by the plugin itself.
